--- <auto-generated>
---     Generated by the moonfly tool.  DO NOT EDIT!
--- </auto-generated>

local M={
    C2SLogin = 1,
    S2CLogin = 2,
    S2CErrorCode = 3,
    C2SEquip = 4,
    S2CEquip = 5,
    C2SUpgradeWeapon = 6,
    S2CUpgradeWeapon = 7,
    C2SGacha = 8,
    S2CGacha = 9,
    C2SPurchasePack = 10,
    S2CPurchasePack = 11,
    S2CUserData = 12,
    C2SBag = 13,
    S2CBag = 14,
    C2SUnEquip = 15,
    S2CUnEquip = 16,

}

local forward = {
    C2SLogin = 'addr_user',
    C2SEquip = 'addr_user',
    C2SUpgradeWeapon = 'addr_user',
    C2SGacha = 'addr_user',
    C2SPurchasePack = 'addr_user',
    C2SBag = 'addr_user',
    C2SUnEquip = 'addr_user',

}

local mt = { forward = forward }

mt.__newindex = function(_, name, _)
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

mt.__index = function(_, name)
    if name == "forward" then
        return forward
    end
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

return setmetatable(M,mt)
