--- <auto-generated>
---     Generated by the moonfly tool.  DO NOT EDIT!
--- </auto-generated>

local M={
    C2SLogin = 1,
    S2CLogin = 2,
    S2CErrorCode = 3,
    S2CItemList = 4,
    C2SEquip = 5,
    S2CEquip = 6,
    C2SUpgradeWeapon = 7,
    S2CUpgradeWeapon = 8,
    C2SGacha = 9,
    S2CGacha = 10,
    C2SPurchasePack = 11,
    S2CPurchasePack = 12,
    S2CUserData = 13,

}

local forward = {
    C2SLogin = 'addr_user',
    C2SEquip = 'addr_user',
    C2SUpgradeWeapon = 'addr_user',
    C2SGacha = 'addr_user',
    C2SPurchasePack = 'addr_user',

}

local mt = { forward = forward }

mt.__newindex = function(_, name, _)
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

mt.__index = function(_, name)
    if name == "forward" then
        return forward
    end
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

return setmetatable(M,mt)
