--- <auto-generated>
---     Generated by the moonfly tool.  DO NOT EDIT!
--- </auto-generated>


---@class AuthUser
---@field public addr_user integer @玩家服务address
---@field public openid string @
---@field public uid integer @玩家uid
---@field public logouttime integer @玩家登出时间,0表示在线
---@field public online boolean @@是否在线


---@class UserData
---@field public openid string @
---@field public uid integer @玩家uid
---@field public name string @玩家名字
---@field public level integer @玩家等级
---@field public exp integer @当前经验
---@field public logintime integer @玩家上线时间
---@field public diamond integer @宝石
---@field public gold integer @金币
---@field public chapterid integer @当前章节ID
---@field public itemlist table<integer, ItemData> @道具列表


---@class ItemData
---@field public id integer @道具id
---@field public config integer @config id
---@field public count integer @道具数量


---@class WeaponData
---@field public id integer @武器id
---@field public config integer @config id
---@field public level integer @等级
---@field public star integer @星级


---@class S2CErrorCode
---@field public code integer @错误码


---@class C2SLogin
---@field public openid string @openid


---@class S2CLogin
---@field public ok boolean @是否登录成功
---@field public time integer @服务器当前时间ms
---@field public timezone integer @服务器当前时区


---@class C2SItemList


---@class S2CItemList
---@field public itemlist ItemData[] @道具列表
---@field public equipedIds integer[] @已装备的id
---@field public weaponlist WeaponData[] @装备列表


---@class C2SEquip
---@field public equipId integer @武器id


---@class S2CEquip
---@field public ok boolean @是否装备成功
---@field public equipId integer @武器id


---@class C2SUpgradeWeapon
---@field public equipId integer @武器id


---@class S2CUpgradeWeapon
---@field public equipId integer
---@field public level integer


---@class C2SGacha
---@field public id integer @宝箱id
---@field public count integer @宝箱个数


---@class S2CGacha
---@field public itemlist ItemData[] @道具列表


---@class C2SPurchasePack
---@field public packId integer @礼包id


---@class S2CPurchasePack
---@field public itemlist ItemData[] @道具列表






---@class auth_scripts
---@field Auth Auth


---@class gate_scripts
---@field Gate Gate


---@class node_scripts
---@field Console Console


---@class user_scripts
---@field Hello Hello
---@field Item Item
---@field Shop Shop
---@field User User
---@field UserModel UserModel
---@field Weapon Weapon


---@class static_conf
---@field constant constant
---@field example example_cfg[]
---@field item item_cfg[]
